version: '3.7'
services:
  telegraf:
    image: telegraf:1.23
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    # depends_on:
    #   - influxdb
    # links:
    #   - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    - '57000:57000'
    - '9273:9273'
    networks:
      - mdt

  # influxdb:
  #   image: influxdb:2.6
  #   env_file: configuration.env
  #   ports:
  #     - '8086:8086'
  #   volumes:
  #     - influxdb_data:/var/lib/influxdb
  #   networks:
  #     - mdt

  grafana:
    image: grafana/grafana:9.0.5
    env_file: configuration.env
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - mdt

volumes:
  grafana_data: {}
  # influxdb_data: {}

networks:
  mdt: