global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.140:9100']
  - job_name: 'telegraf'
    static_configs:
      - targets: [192.168.100.242:9273]
